### ISSUE TITLE
README need a example

### ISSUE THREAD

**Issue by b3g00d** [dgarana/thumbor-aliases#1]
I'm using `thumbor-aliases` and it doesn't work as I expected.
Found out I need a prefix `\a\alias` to make it work.
Please update your example README.

**Comment by dgarana** [comment]
Totally agree. Do you want to create a pull request for that?

**Comment by b3g00d** [comment]
I'm dealing with another bug or feature
look like your regex doesn't work with `\unsafe\a\alias`
```
r'/unsafe/(?P<resolution>[^\/]+)/a/(?P<alias>[^\/]+)/?(?P<img_url>.+)?'
```
I trying bypass with this, but I need to auto detect with config for that.

**Comment by b3g00d** [comment]
Please review #2

**Comment by dgarana** [comment]
Change merged. Thanks for contributing :)
